/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wificlient;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Starting");

        int port = 2222;
        String host = "10.0.1.1";
        
        Legobil lego = new Legobil(host, port);
        lego.send("heeeellllooooo");

        // String input;
        // while ((input = lego.read()) != null) {
        //     System.out.println(input);
        // }

        lego.disconnect();
    }
}
